apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: app
data:
  PGDB_HOST: postgres.db.svc.cluster.local
  PGDB_USER: postgres
  PGDB_NAME: mydb
  REDIS_HOST: redis.redis.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: app
type: Opaque
stringData:
  PGDB_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: meghanapatel2701/app-container:latest
        ports:
        - containerPort: 5000
        env:
        - name: PGDB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: PGDB_HOST
        - name: PGDB_USER
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: PGDB_USER
        - name: PGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: PGDB_PASSWORD
        - name: PGDB_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: PGDB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: app
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
